export default {
  // light: {
  colors: {
    yellow_light: '#F1E9C9',
    yellow: '#DBAC2C',
    yellow_dark: '#C47F17',
    purple_light: '#EBE5F9',
    purple: '#8047F8',
    purple_dark: '#4B2995',
    base_card: '#F3F2F2',
    base_input: '#EDEDED',
    base_button: '#E6E5E5',
    base_hover: '#D7D5D5',
    base_label: '#8D8686',
    base_text: '#574F4D',
    base_subtitle: '#403937',
    base_tilte: '#272221',
    background: '#FAFAFA',
    white: '#FFF',
  },
  fonts: {
    title_xl: "800 4.8rem/130% 'Baloo 2', cursive",
    title_l: "800 3.2rem/130% 'Baloo 2', cursive",
    title_m: "800 2.4rem/130% 'Baloo 2', cursive",
    title_s: "bold 2.0rem/130% 'Baloo 2', cursive",
    title_xs: "bold 1.8rem/130% 'Baloo 2', cursive",
    text_regular_l: "2.0rem/130% 'Roboto', sans-serif",
    text_bold_l: "bold 2.0rem/130% 'Roboto', sans-serif",
    text_regular_m: "1.6rem/130% 'Roboto', sans-serif",
    text_bold_m: "bold 1.6rem/130% 'Roboto', sans-serif",
    text_regular_s: "1.4rem/130% 'Roboto', sans-serif",
    text_bold_s: "bold 1.2rem/130% 'Roboto', sans-serif",
    tag: "bold 1.0rem/130% 'Roboto', sans-serif",
    button_l: "bold 1.4rem/160% 'Roboto', sans-serif",
    button_s: "bold 1.2rem/160% 'Roboto', sans-serif",
    sizes: {
      xxsmall: 10,
      xsmall: 12,
      small: 14,
      medium: 16,
      xmedium: 18,
      xxmedium: 20,
      large: 24,
      xlarge: 32,
      xxlarge: 48,
    },
  },
  // },
  // dark: {
  //   colors: {
  //     yellow_light: '#F1E9C9',
  //     yellow: '#DBAC2C',
  //     yellow_dark: '#C47F17',
  //     purple_light: '#EBE5F9',
  //     purple: '#8047F8',
  //     purple_dark: '#4B2995',
  //     base_card: '#F3F2F2',
  //     base_input: '#EDEDED',
  //     base_button: '#E6E5E5',
  //     base_hover: '#D7D5D5',
  //     base_label: '#8D8686',
  //     base_text: '#574F4D',
  //     base_subtitle: '#403937',
  //     base_tilte: '#272221',
  //     background: '#FAFAFA',
  //     white: '#FFF',
  //   },
  //   fonts: {
  //     title_xl: "800 4.8rem/130% 'Baloo 2', cursive",
  //     title_l: "800 3.2rem/130% 'Baloo 2', cursive",
  //     title_m: "800 2.4rem/130% 'Baloo 2', cursive",
  //     title_s: "bold 2.0rem/130% 'Baloo 2', cursive",
  //     title_xs: "bold 1.8rem/130% 'Baloo 2', cursive",
  //     text_regular_l: "2.0rem/130% 'Roboto', sans-serif",
  //     text_bold_l: "bold 2.0rem/130% 'Roboto', sans-serif",
  //     text_regular_m: "1.6rem/130% 'Roboto', sans-serif",
  //     text_bold_m: "bold 1.6rem/130% 'Roboto', sans-serif",
  //     text_regular_s: "1.4rem/130% 'Roboto', sans-serif",
  //     text_bold_s: "bold 1.2rem/130% 'Roboto', sans-serif",
  //     tag: "1.0rem/130% 'Roboto', sans-serif",
  //     button_l: "bold 1.4rem/160% 'Roboto', sans-serif",
  //     button_s: "bold 1.2rem/160% 'Roboto', sans-serif",
  //     sizes: {
  //       xxsmall: 10,
  //       xsmall: 12,
  //       small: 14,
  //       medium: 16,
  //       xmedium: 18,
  //       xxmedium: 20,
  //       large: 24,
  //       xlarge: 32,
  //       xxlarge: 48,
  //     },
  //   }
  // }
} as const
